# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Feelpp for Ubuntu 24.04 (noble)
ARG ROOT_CONTAINER=ghcr.io/feelpp/feelpp:v0.111.0-preview.10-noble

FROM $ROOT_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# # set proper groups for opengl support
# ARG VGLUSERS="vglusers"
# ARG VGLUSERS_GID="1001"

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# Install all OS dependencies for the Server that starts
# but lacks all features (e.g., download as all possible file formats)
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update --yes && \
    # - `apt-get upgrade` is run to patch known vulnerabilities in system packages
    #   as the Ubuntu base image is rebuilt too seldom sometimes (less than once a month)
    apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends \
    # - bzip2 is necessary to extract the micromamba executable.
    bzip2 \
    ca-certificates \
    locales \
    # - `netbase` provides /etc/{protocols,rpc,services}, part of POSIX
    #   and required by various C functions like getservbyname and getprotobyname
    #   https://github.com/jupyter/docker-stacks/pull/2129
    netbase \
    sudo \
    # - `tini` is installed as a helpful container entrypoint,
    #   that reaps zombie processes and such of the actual executable we want to start
    #   See https://github.com/krallin/tini#why-tini for details
    tini \
    wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "C.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

# Install python (nb feelpp is already installed)
RUN apt-get update --yes && \
    apt-get upgrade && \ 
    apt-get -y install python-is-python3 python3-venv python3-xvfbwrapper && \
    apt-get -y install libpci3 mesa-utils libegl1 libegl1-mesa-dev libxrender1 xvfb && \
    apt-get -y install nodejs nmap && \
    apt-get -y install wget curl gpg sudo
    
# eventually add a web browser
# RUN apt-get -y install firefox-esr 

# Configure environment
ENV SHELL=/bin/bash \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8
ENV PATH="/home/feelpp/jupyterlab-env/bin:${PATH}" \
    HOME="/home/feelpp"
    

# Enable prompt color in the skeleton .bashrc before creating the default NB_USER
# hadolint ignore=SC2016
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc

# JUPYTER_TOKEN=token
ENV JUPYTER_PORT=8888
EXPOSE $JUPYTER_PORT

USER feelpp

# setup virtualenv for jupyter
RUN cd /home/feelpp && \
    python3 -m venv --system-site-packages /home/feelpp/jupyterlab-env && \
    . jupyterlab-env/bin/activate && \
    python3 -m pip install jupyterhub jupyterlab nbclassic notebook jupyter-server-proxy trame-jupyter-extension \
    	    pyvista[all] \
    	    gmsh && \
    jupyter server --generate-config && \
    jupyter lab clean && \
    deactivate


# Copy local files as late as possible to avoid cache busting
COPY run-hooks.sh start.sh /usr/local/bin/

USER root

# Create dirs for startup hooks
RUN mkdir /usr/local/bin/start-notebook.d && \
    mkdir /usr/local/bin/before-notebook.d


# Switch back to jovyan to avoid accidental container runs as root
USER feelpp
COPY start-venv.sh ${HOME}
COPY start ${HOME}

WORKDIR "${HOME}"

# Configure container entrypoint
# ENTRYPOINT ["tini", "-g", "--", "./start-venv.sh"]

# docker run -it --rm --gpus all -e NVIDIA_DRIVER_CAPABILITIES=all  -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -p 8888:8888 --name jupylab jupylab:pip
# to get access from outside the container: jupyter lab  --ip="0.0.0.0"
# chromium -incognito http://127.0.0.1:8888/lab?token=493c2f3e07fbbde3e31ef24b055ce5bfe4bb9d6dd285af59
# firefox -private-windows http://127.0.0.1:8888/lab?token=493c2f3e07fbbde3e31ef24b055ce5bfe4bb9d6dd285af59